# Generated by Django 5.1.4 on 2025-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_qrsession_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
