# Generated by Django 5.1.4 on 2025-02-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrsession',
            name='session_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Oturum Numarası'),
        ),
    ]
